[package]
name = "version_control"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
uuid = { version = "1.0", features = ["v4"] }
walkdir = "2.3"

